name: terraform-ci

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-validate-ci.yaml"

  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-validate-ci.yaml"

permissions:
  contents: read

jobs:
  terraform-ci:
    name: Terraform CI
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        environment:
          - local
          - dev
          - staging
          - uat
          - prod

    defaults:
      run:
        working-directory: terraform/environments/${{ matrix.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Setup Kind
        uses: helm/kind-action@v1
        with:
          cluster_name: online-boutique

      - name: Check Terraform formatting
        run: terraform fmt -check -recursive

      - name: Initialize Terraform
        run: terraform init -backend=false

      - name: Validate Terraform
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false \
          -var="namespace_name=platform-${{ matrix.environment }}" \
          -var="environment=${{ matrix.environment }}"
